version: 1
update_configs:
  - package_manager: "submodules"
    directory: "./"
    update_schedule: "daily"
    allowed_updates:
    ignored_updates:
      - match:
          dependency_name: "6-grading-tests"
