name: Grading

on:
  pull_request:
    branches: [ master ]

jobs:
  grading-test:
    runs-on: ubuntu-latest
    container: vladimirkutuev/cmocka:latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 2      
          token: ${{ secrets.PAT }}
      - name: Check repository clean
        run: ./6-grading-tests/script/check_clean.sh
      - name: Test with memcheck
        run: ./6-grading-tests/script/test.sh

